// Generated by gencpp from file cone_detection/Cone3dArray.msg
// DO NOT EDIT!


#ifndef CONE_DETECTION_MESSAGE_CONE3DARRAY_H
#define CONE_DETECTION_MESSAGE_CONE3DARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <cone_detection/Cone3d.h>

namespace cone_detection
{
template <class ContainerAllocator>
struct Cone3dArray_
{
  typedef Cone3dArray_<ContainerAllocator> Type;

  Cone3dArray_()
    : header()
    , cones()  {
    }
  Cone3dArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , cones(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::cone_detection::Cone3d_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::cone_detection::Cone3d_<ContainerAllocator> >> _cones_type;
  _cones_type cones;





  typedef boost::shared_ptr< ::cone_detection::Cone3dArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cone_detection::Cone3dArray_<ContainerAllocator> const> ConstPtr;

}; // struct Cone3dArray_

typedef ::cone_detection::Cone3dArray_<std::allocator<void> > Cone3dArray;

typedef boost::shared_ptr< ::cone_detection::Cone3dArray > Cone3dArrayPtr;
typedef boost::shared_ptr< ::cone_detection::Cone3dArray const> Cone3dArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cone_detection::Cone3dArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cone_detection::Cone3dArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cone_detection::Cone3dArray_<ContainerAllocator1> & lhs, const ::cone_detection::Cone3dArray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.cones == rhs.cones;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cone_detection::Cone3dArray_<ContainerAllocator1> & lhs, const ::cone_detection::Cone3dArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cone_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cone_detection::Cone3dArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cone_detection::Cone3dArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cone_detection::Cone3dArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cone_detection::Cone3dArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cone_detection::Cone3dArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cone_detection::Cone3dArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cone_detection::Cone3dArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4e94f7d77cdaef26bbe5fc5386a06674";
  }

  static const char* value(const ::cone_detection::Cone3dArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4e94f7d77cdaef26ULL;
  static const uint64_t static_value2 = 0xbbe5fc5386a06674ULL;
};

template<class ContainerAllocator>
struct DataType< ::cone_detection::Cone3dArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cone_detection/Cone3dArray";
  }

  static const char* value(const ::cone_detection::Cone3dArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cone_detection::Cone3dArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"Cone3d[] cones\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: cone_detection/Cone3d\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 confidence\n"
"int32 class_id\n"
;
  }

  static const char* value(const ::cone_detection::Cone3dArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cone_detection::Cone3dArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.cones);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cone3dArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cone_detection::Cone3dArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cone_detection::Cone3dArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "cones[]" << std::endl;
    for (size_t i = 0; i < v.cones.size(); ++i)
    {
      s << indent << "  cones[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::cone_detection::Cone3d_<ContainerAllocator> >::stream(s, indent + "    ", v.cones[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONE_DETECTION_MESSAGE_CONE3DARRAY_H
