// Generated by gencpp from file cone_detection/DriveCmd.msg
// DO NOT EDIT!


#ifndef CONE_DETECTION_MESSAGE_DRIVECMD_H
#define CONE_DETECTION_MESSAGE_DRIVECMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cone_detection
{
template <class ContainerAllocator>
struct DriveCmd_
{
  typedef DriveCmd_<ContainerAllocator> Type;

  DriveCmd_()
    : throttle(0.0)
    , steering(0.0)  {
    }
  DriveCmd_(const ContainerAllocator& _alloc)
    : throttle(0.0)
    , steering(0.0)  {
  (void)_alloc;
    }



   typedef float _throttle_type;
  _throttle_type throttle;

   typedef float _steering_type;
  _steering_type steering;





  typedef boost::shared_ptr< ::cone_detection::DriveCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cone_detection::DriveCmd_<ContainerAllocator> const> ConstPtr;

}; // struct DriveCmd_

typedef ::cone_detection::DriveCmd_<std::allocator<void> > DriveCmd;

typedef boost::shared_ptr< ::cone_detection::DriveCmd > DriveCmdPtr;
typedef boost::shared_ptr< ::cone_detection::DriveCmd const> DriveCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cone_detection::DriveCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cone_detection::DriveCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cone_detection::DriveCmd_<ContainerAllocator1> & lhs, const ::cone_detection::DriveCmd_<ContainerAllocator2> & rhs)
{
  return lhs.throttle == rhs.throttle &&
    lhs.steering == rhs.steering;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cone_detection::DriveCmd_<ContainerAllocator1> & lhs, const ::cone_detection::DriveCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cone_detection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cone_detection::DriveCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cone_detection::DriveCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cone_detection::DriveCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cone_detection::DriveCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cone_detection::DriveCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cone_detection::DriveCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cone_detection::DriveCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "170b15dad834e867dc37649de9ec28b1";
  }

  static const char* value(const ::cone_detection::DriveCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x170b15dad834e867ULL;
  static const uint64_t static_value2 = 0xdc37649de9ec28b1ULL;
};

template<class ContainerAllocator>
struct DataType< ::cone_detection::DriveCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cone_detection/DriveCmd";
  }

  static const char* value(const ::cone_detection::DriveCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cone_detection::DriveCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 throttle\n"
"float32 steering\n"
;
  }

  static const char* value(const ::cone_detection::DriveCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cone_detection::DriveCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.throttle);
      stream.next(m.steering);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DriveCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cone_detection::DriveCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cone_detection::DriveCmd_<ContainerAllocator>& v)
  {
    s << indent << "throttle: ";
    Printer<float>::stream(s, indent + "  ", v.throttle);
    s << indent << "steering: ";
    Printer<float>::stream(s, indent + "  ", v.steering);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONE_DETECTION_MESSAGE_DRIVECMD_H
